### ISSUE TITLE
Unexpected artifact file

### ISSUE THREAD

**Issue by jruaux** [jreleaser/release-action#4]
I've added a VERSION file to my project like JReleaser does but for some reason the file that shows up in the early-access release is the one from JReleaser (0.6.0) and not the one from my project (2.12.1-SNAPSHOT).

https://github.com/redis-developer/riot/releases/tag/early-access

Do you have any idea what might be happening here?

**Comment by aalmiray** [comment]
The problem is caused by the mechanism used by the`release-action` to determine the latest version. It downloads a "VERSION" file from https://jreleaser.org/releases/latest/download/VERSION, effectively clobbering your own "VERSION" file. This only happens when no explicit version is given to the `release-action` (hence it assumes "latest").

A temporary workaround til this issue is fixes is to explicitly define a version parameter to the release action.

**Comment by aalmiray** [comment]
The problem is fixed. It's available on the latest version of this action(`1.4.0`) as well as on the `v1` branch. You don't have to update your workflows to get the latest version.

**Comment by jruaux** [comment]
Nice! Thanks for the quick turnaround
